# Generated by Django 4.0.2 on 2022-03-11 22:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mascotas_mascota_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='mascota_img',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='Imagen'),
        ),
    ]
